name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  cloud_firestore: any
  cupertino_icons: ^1.0.6
  http: any
  url_launcher: any
  video_player: any
  youtube_player_flutter: any
  geocoding: any
  geolocator: any
  flutter_map: any
  latlong2: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

# ตั้งค่าไอคอนแอป (ต้องมั่นใจว่ามีไฟล์ assets/heart.png อยู่จริง)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/heart.png"