name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  url_launcher: ^6.2.1
  video_player: ^2.8.1
  youtube_player_flutter: ^9.1.3
  geocoding: ^4.0.0
  geolocator: ^14.0.2  # แก้ไขเวอร์ชันให้ถูกต้อง
  flutter_map: 5.0.0
  latlong2: ^0.9.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.0   # แก้เวอร์ชันให้เสถียรขึ้น

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/01.png
    - assets/02.jpg
    - assets/03.jpg
    - assets/04.jpg
    - assets/05.jpg
    - assets/07.jpg
    - assets/06.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/heart.png"